version: "3.3"

services:
  web:
    tty: true
    stdin_open: true
    image: node:14-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: npm install && npm start